# Generated by Django 2.1b1 on 2019-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casetask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=150, verbose_name='标题')),
                ('creater', models.CharField(default='', max_length=20, verbose_name='创建人')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('run_time', models.CharField(default='', max_length=20, verbose_name='运行时间')),
                ('case_path', models.CharField(default='', max_length=100, verbose_name='路径')),
                ('desc', models.TextField(default='', verbose_name='描述')),
                ('timestamp', models.DateTimeField(default='')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Runlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(default='', max_length=20, verbose_name='任务id')),
                ('report_title', models.CharField(default='', max_length=150, verbose_name='报告名称')),
                ('report_path', models.CharField(default='', max_length=150, verbose_name='报告路径')),
                ('desc', models.TextField(default='', verbose_name='报告描述')),
                ('timestamp', models.DateTimeField(default='')),
            ],
        ),
    ]
