# Generated by Django 2.1b1 on 2019-05-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfmtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casetask',
            old_name='id',
            new_name='cid',
        ),
    ]
